[project]
name = "advanced-earth-science-data-analysis"
version = "0.2.0"
description = "Advanced Earth Science Data Analysis Course Materials"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cartopy>=0.24.1",
    "cftime>=1.6.4.post1",
    "cmocean>=4.0.3",
    "dask>=2025.5.1",
    "descartes>=1.1.0",
    "fastkde>=2.1.5",
    "geopandas>=1.1.1",
    "gitpython>=3.1.44",
    "gitsummary>=0.2",
    "h5netcdf>=1.6.3",
    "ipykernel>=6.29.5",
    "ipython>=9.4.0",
    "jupyter-book>=1.0.4.post1",
    "matplotlib>=3.10.3",
    "mpi4py>=4.1.0",
    "netcdf4>=1.7.2",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "pip>=25.1.1",
    "scipy>=1.16.0",
    "seaborn>=0.13.2",
    "setuptools>=80.9.0",
    "shapely>=2.1.1",
    "simplempi>=0.1.5",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
    "xarray>=2025.7.1",
]
