channels:
 - conda-forge
dependencies:
 - cartopy #plotting geospatial data
 - cftime #handling non-standard calendars
 - cmocean #more perceptually-uniform colorbars
 - dask #distributed (larger than memory) dataset handling
 - descartes #add geometric patch support to matplotlib
 - geopandas #geospatial data analysis
 - gitpython #python git interface
 - h5netcdf #use the h5netcdf engine in xarray (compression, speed)
 - ipython # interactive python terminal
 - ipykernel # for running jupyter notebook kernels in vscode
 - matplotlib #low-level plotting interface
 - mpi4py #python bindings for MPI
 - netcdf4 #low-level handling of netCDF files
 - numpy #low-level, fast array handling
 - openh264 #H.264 codec support
 - pandas #time-series analysis
 - pip #python package manager
 - scipy #interpolation, statistics, linear algebra, signal processing, special funcs
 - seaborn #high-level plotting
 - setuptools #python package development
 - shapely #low-level shape handling
 - x264 #video codec
 - xarray #high-level gridded data handling/analysis/processing, supports NETCDF/GRIB and more
 - pip: #pip dependencies
   - fastkde #fast Kernel Density Estimation
   - gitsummary # makes it simple to print git repo info in a notebook or script